---
swagger: "2.0"
info:
  version: 1.0.0
  title: AWS-S3
host: virtserver.swaggerhub.com
basePath: /unisens4/aws-s3/1.0.0
schemes:
- https
paths:
  /download/{folder}/{filename}:
    get:
      produces:
      - application/json
      parameters:
      - name: filename
        in: path
        required: true
        type: string
      - name: folder
        in: path
        required: true
        type: string
      responses:
        "200":
          description: 200 response
          headers:
            content-type:
              type: string
            Content-Type:
              type: string
          schema:
            $ref: '#/definitions/Empty'
        "400":
          description: 400 response
        "500":
          description: 500 response
      x-amazon-apigateway-integration:
        credentials: arn:aws:iam::732086524086:role/apigAwsProxyRole
        responses:
          "4\\d{2}":
            statusCode: "400"
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.content-type: integration.response.header.content-type
              method.response.header.Content-Type: integration.response.header.Content-Type
          "5\\d{2}":
            statusCode: "500"
        requestParameters:
          integration.request.path.object: method.request.path.filename
          integration.request.path.bucket: method.request.path.folder
        uri: https://gentle-shelf-66601.herokuapp.com/download/
        passthroughBehavior: when_no_match
        httpMethod: GET
        type: aws
  /upload:
    post:
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: false
        type: string
      responses:
        "200":
          description: 200 response
          headers:
            Content-Length:
              type: string
            Content-Type:
              type: string
          schema:
            $ref: '#/definitions/Empty'
        "400":
          description: 400 response
        "500":
          description: 500 response
      x-amazon-apigateway-integration:
        credentials: arn:aws:iam::732086524086:role/apigAwsProxyRole
        responses:
          "4\\d{2}":
            statusCode: "400"
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Content-Length: integration.response.header.Content-Length
          "5\\d{2}":
            statusCode: "500"
        requestParameters:
          integration.request.path.object: method.request.path.filename
          integration.request.path.bucket: method.request.path.folder
          integration.request.header.Content-Type: method.request.header.Content-Type
        uri: arn:aws:apigateway:us-west-2:s3:path/{bucket}/{object}
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws
definitions:
  Empty:
    type: object
    title: Empty Schema
